import os
import argparse
import pickle
import random
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, RandomizedSearchCV
from sklearn.ensemble import RandomForestClassifier
from scipy.stats.distributions import randint
from utils import encode_types

def hyper_params_search(X_train, y_train, save_path):
    """
    Performs a randomized search for the best hyper parameters, validating the search using k-fold cross validation.
    It also saves the model trained with the best found parameters on the whole training set.

    Parameters:
    - X_train: array with training features.
    - y_train: array with tarining labels.
    - save_path: path to the file where to save the model trained with best found parameters on the whole training set.
    """

    # perform a grid search to find the best set of hyper-parameters using cross validation
    hyper_params_grid = {"n_estimators": randint(50, 1000), "max_depth": randint(1, 30)}
    clf = RandomForestClassifier()
    random_search = RandomizedSearchCV(clf, param_distributions=hyper_params_grid, n_iter=20, cv=5, verbose=4, n_jobs=8)
    random_search.fit(X_train, y_train)
    print(f"\nBest hyperparameters: {random_search.best_params_}")

    # save the model
    with open(save_path, "wb") as file:
        pickle.dump(random_search.best_estimator_, file)
    
    # return the best estimator re-trained on the whole training set
    return random_search.best_estimator_

def parse_args():
    """
    Parses command line arguments.

    Returns:
    - parser.parse_args(): ArgumentParser object with parsed arguments.
    """

    # create the argument parser
    parser = argparse.ArgumentParser(description="Splits data into training ad test sets and trains a model on data collected from a simulation.")

    # arguments
    parser.add_argument("-i", "--input_data", type=str, required=False, default=os.path.join("..", "data", "collected_data.csv"), help="Path to the input dataset with data collected from a simulation.")
    parser.add_argument("-t", "--test_indices_path", type=str, required=False, default=os.path.join("..", "data", "test_indices.npy"), help="Path to the ifile where to save test indices.")
    parser.add_argument("-m", "--model_path", type=str, required=False, default=os.path.join("..", "model", "model.pickle"), help="Path to the file where to save the trained model.")
    parser.add_argument("-r", "--random_seed", type=int, required=False, default=27, help="Random seed for reproducibility.")
                          
    return parser.parse_args()

if __name__ == '__main__':

    # pars command line arguments
    args = parse_args()

    # set the random seed for reproducibility
    random.seed(args.random_seed)
    np.random.seed(args.random_seed)

    # load the data generated by the simulation
    print("Loading data ...")
    dataset = pd.read_csv(args.input_data)

    # create the folder where to save the model if it does not exist yet
    os.makedirs(os.path.dirname(args.model_path), exist_ok=True)

    # encode the pokemon types
    print("Preparing data ...")
    dataset = encode_types(dataset)

    # extract features and battle outcomes
    X = dataset.drop(columns=["outcome", "game", "battle"])
    y = dataset["outcome"]

    # split data into a training and a test set and save the indices of test samples
    test_ratio = 0.2
    indices = X.index.to_numpy()
    X_train, X_test, y_train, y_test, indices_train, indices_test = train_test_split(X, y, indices, test_size=test_ratio, random_state=args.random_seed)
    np.save(args.test_indices_path, indices_test)

    # select the hyper parameters by performing a randomized search with k-fold cross validation and re-train the model on the whole training set
    print("Performing a randomized hyper parameters search and training a model with the best found hyper parameters ...")
    hyper_params_search(X_train, y_train, args.model_path)
